export const API_CALL = "API_CALL";

export const SHOW_FREEDA = "SHOW_FREEDA";

export const PAGE_INCREMENT = "PAGE_INCREMENT";
export const PAGE_DECREMENT = "PAGE_DECREMENT";

export const LOADING = "LOADING";
export const FETCH_USER_CALLBOOK_SUCCESS = "FETCH_USER_CALLBOOK_SUCCESS";
export const FETCH_USER_CALLBOOK_FAILURE = "FETCH_USER_CALLBOOK_FAILURE";

export const FETCH_REMAINING_SUMMARY_SUCCESS =
  "FETCH_REMAINING_SUMMARY_SUCCESS";
export const FETCH_REMAINING_SUMMARY_FAILURE =
  "FETCH_REMAINING_SUMMARY_FAILURE";

export const SEARCH_API_CALL = "SEARCH_API_CALL";
export const SEARCH_SUCCESSFUL = "SEARCH_SUCCESSFUL";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
